### ISSUE TITLE
Not working on Hogfather rc

### ISSUE THREAD

**Issue by timatengage** [dwp-forge/columns#5] opened 2020-06-02 09:30 UTC
Updated my wiki to the Hogfather release candidate and my columns are no longer columns. They wrap under each other.

**Comment by gdighton** [comment] 2020-06-02 23:26
I don't even get that much - upon update to Hogfather, I can no longer access my wiki at all, as the webserver (nginx) receives a fatal error from PHP and returns nothing but an empty page for all pages.

From the webserver's error log (with identifying information censored):

2020/06/02 16:13:01 [error] 28576#28576: *274 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of syntax_plugin_columnlist::handle$($match, $state, $pos, &$handler) must be compatible with dokuwiki\Extension\SyntaxPlugin::handle($match, $state, $pos, Doku_Handler $handler) in /var/www/wiki/dokuwiki/lib/plugins/columnlist/syntax.php on line 0" while reading response header from upstream, client: XXX.XXX.X.XXX, server: XXXXX, request: "GET /dokuwiki/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "XXX.XXXX.XXX"

**Comment by timatengage** [comment] 2020-06-03 08:51
> 
> 
> I don't even get that much - upon update to Hogfather, I can no longer access my wiki at all, as the webserver (nginx) receives a fatal error from PHP and returns nothing but an empty page for all pages.
> 
> From the webserver's error log (with identifying information censored):
> 
> 2020/06/02 16:13:01 [error] 28576#28576: *274 FastCGI sent in stderr: "PHP message: PHP Fatal error: Declaration of syntax_plugin_columnlist::handle$($match, $state, $pos, &$handler) must be compatible with dokuwiki\Extension\SyntaxPlugin::handle($match, $state, $pos, Doku_Handler $handler) in /var/www/wiki/dokuwiki/lib/plugins/columnlist/syntax.php on line 0" while reading response header from upstream, client: XXX.XXX.X.XXX, server: XXXXX, request: "GET /dokuwiki/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "XXX.XXXX.XXX"

I had a similar error with another plugin, removed the plugin folder and it started working again. It doesn't look like @dwp-forge has been active on github since 2016 so unlikely to be fixed.

**Comment by arlt** [comment] 2020-06-03 09:11
Content is displayed, but no columns and no alignment. One empty line after each column/row.

Log (warnings only):
```
PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER' (this will throw an Error in a future version of PHP) in /var/www/dokuwiki/lib/plugins/columns/syntax.php on line 49
PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_MATCHED - assumed 'DOKU_LEXER_MATCHED' (this will throw an Error in a future version of PHP) in /var/www/dokuwiki/lib/plugins/columns/syntax.php on line 50
PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT' (this will throw an Error in a future version of PHP) in /var/www/dokuwiki/lib/plugins/columns/syntax.php on line 51', referer: https://fqdn/wiki/plugins
```

**Comment by splitbrain** [comment] 2020-06-03 09:33
The problem @gdighton is describing is not a Hogfather related problem but simply the result of PHP's stricter signature checking since 7.x. Signatures of the plugins need adjustment.

@arlt's problem is indeed a problem, however I have no idea why those constants shouldn't be defined. They still exist in Hogfather.

**Comment by dwp-forge** [comment] 2020-06-03 21:18
@splitbrain, now I got you where I want you ;)

I saw this issue months ago but I was waiting for release to see if it will get resolved somehow. Actually, I expected that lots of syntax plugins will be affected by it, but apparently I do something not according to the book even though I pretty much follow [the skeleton](https://www.dokuwiki.org/devel:syntax_plugin_skeleton) (BTW, it's time to update the deprecated require_once).

The thing is that before refactoring syntax plugins would require `lib/plugins/syntax.php`, which would auto-load `inc/parser/parser.php`, which would require `inc/parser/lexer.php`. This way `DOKU_LEXER_*` constants would be defined by just requiring `syntax.php`.

Now in our new shiny auto-load land `syntax.php` is deprecated and per my understanding `inc/Extension/SyntaxPlugin.php` auto-loads bunch of stuff related to Handler and Renderer, but Lexer somehow is not involved at that stage. So it looks like by the time plugin's constructor is executed, no one yet asked for Lexer class and it didn't get auto-loaded. And as a side effect the constants are not defined. Unfortunately, auto-loader doesn't know anything about them.

I can work it around by explicitly requiring `inc/Parsing/Lexer/Lexer.php` but that goes against the auto-loading paradigm. Also to me this looks like a broken contract between framework and plugin, so I was wondering if something will be done on the framework side to address this issue.

Any thoughts on that?

**Comment by gdighton** [comment] 2020-06-09 21:16
Still not working on latest RC due to the signature issue. @splitbrain claims this is a php issue, but php version is the same whether I'm using Greebo or Hogfather, and it's only a fatal error on Hogfather:

$ php --version
PHP 7.3.14-1~deb10u1 (cli) (built: Feb 16 2020 15:07:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.14-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by dwp-forge** [comment] 2020-06-09 21:53
Fixed upstream in Hogfather RC3.

**Comment by dwp-forge** [comment] 2020-06-09 22:23
@gdighton, I tested on PHP 7.2 and that seem to work fine. Based on my analysis of the issue and the way it was addressed in RC3 it looks to me that the problem should be properly fixed. Unless someone else will be able to reproduce it, I would assume there's some local problem on your setup.

If you feel like debugging it, you could check which files are included before you run into the problem. Per my understanding, new file `inc/defines.php` is included unconditionally, so it should be there:

```
  0 => '/home/dwp-forge/hogfather/doku.php',
  1 => '/home/dwp-forge/hogfather/inc/init.php',
  2 => '/home/dwp-forge/hogfather/inc/config_cascade.php',
  3 => '/home/dwp-forge/hogfather/conf/dokuwiki.php',
  4 => '/home/dwp-forge/hogfather/conf/local.php',
  5 => '/home/dwp-forge/hogfather/conf/license.php',
  6 => '/home/dwp-forge/hogfather/vendor/autoload.php',
  7 => '/home/dwp-forge/hogfather/vendor/composer/autoload_real.php',
  8 => '/home/dwp-forge/hogfather/vendor/composer/ClassLoader.php',
  9 => '/home/dwp-forge/hogfather/vendor/composer/autoload_static.php',
  10 => '/home/dwp-forge/hogfather/vendor/openpsa/universalfeedcreator/lib/constants.php',
  11 => '/home/dwp-forge/hogfather/vendor/paragonie/random_compat/lib/random.php',
  12 => '/home/dwp-forge/hogfather/vendor/phpseclib/phpseclib/phpseclib/bootstrap.php',
  13 => '/home/dwp-forge/hogfather/inc/load.php',
  14 => '/home/dwp-forge/hogfather/inc/defines.php',  <------ This one
  15 => '/home/dwp-forge/hogfather/inc/actions.php',
  16 => '/home/dwp-forge/hogfather/inc/changelog.php',
  17 => '/home/dwp-forge/hogfather/inc/common.php',
...
```

**Comment by dwp-forge** [comment] 2020-06-14 17:10
@gdighton, the issue you are referring to was fixed back in 2016 (ba677268fa). Please make sure that you run latest version of the plugin. Verified on PHP 7.4.

**Comment by gdighton** [comment] 2020-06-15 15:14
According to the Extension Manager, I am using the latest (and I installed the plugin less than a year ago.)

Plugin.info.txt says:
base   columns
author Mykola Ostrovskyy
email  spambox03@mail.ru
date   2016-09-07
name   Columns Plugin
desc   Arrange information in multiple columns.
url    http://www.dokuwiki.org/plugin:columns

**Comment by dwp-forge** [comment] 2020-06-15 22:05
That looks good. Now what about plugin name in your problem report? Let's make sure it's named "columns" and not something else. Like "[columnlist](https://www.dokuwiki.org/plugin:columnlist)" or something ;)

**Comment by arlt** [comment] 2020-06-16 06:13
@splitbrain @dwp-forge fixed with RC3

**Comment by gdighton** [comment] 2020-06-16 15:59
@dwp-forge Ah, dang - looks like I misread it way back when... Now I have to find their github page :-)

**Closed** 2020-06-16 17:38 UTC
Labels: bug
